import Link from "next/link";
import { CheckCircle2, ChevronRight } from "lucide-react";
import { Button, Card, CardContent } from "@/components/ui";
import { sampleOffer } from "./data";
import { formatCurrency } from "./format";
import { OfferStatusBadge } from "./components/offer-status-badge";
import { OfferVehicleSummary } from "./components/offer-vehicle-summary";
import type { OfferVehicle } from "./types";

export function OfferSubmittedPage({ vehicle, amount }: { vehicle: OfferVehicle; amount: number }) {
  return <main className="min-h-screen bg-ivory"><section className="px-4 py-10 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto grid max-w-5xl gap-8 lg:grid-cols-[minmax(0,1fr)_360px]"><div><div className="flex size-14 items-center justify-center rounded-full bg-success/15 text-success"><CheckCircle2 aria-hidden="true" size={32} /></div><p className="mt-7 text-xs font-black uppercase tracking-[0.16em] text-brand">Sample offer flow</p><h1 className="mt-3 font-display text-5xl font-black uppercase tracking-[-0.06em]">Offer sent</h1><p className="mt-6 text-4xl font-black text-brand">{formatCurrency(amount)}</p><p className="mt-3 text-lg text-muted">Your offer has been sent to the seller.</p><div className="mt-7"><OfferStatusBadge status="PENDING" /></div><Card className="mt-7 max-w-xl"><CardContent className="grid gap-5 p-6 sm:grid-cols-3"><div><p className="text-xs font-bold text-muted">Offer ID</p><p className="mt-1 text-sm font-black">{sampleOffer.id}</p></div><div><p className="text-xs font-bold text-muted">Sent</p><p className="mt-1 text-sm font-black">{sampleOffer.sentAt}</p></div><div><p className="text-xs font-bold text-muted">Expires</p><p className="mt-1 text-sm font-black">{sampleOffer.expiresAt}</p></div></CardContent></Card><Card className="mt-5 max-w-xl"><CardContent className="p-6"><h2 className="text-xl font-black">What the seller can do</h2><ul className="mt-4 space-y-3 text-sm"><li className="flex items-center gap-2"><ChevronRight aria-hidden="true" className="text-success" size={17} />Accept</li><li className="flex items-center gap-2"><ChevronRight aria-hidden="true" className="text-success" size={17} />Reject</li><li className="flex items-center gap-2"><ChevronRight aria-hidden="true" className="text-success" size={17} />Counter your offer</li></ul></CardContent></Card><p className="mt-6 text-sm font-bold text-success">You don&apos;t need to pay anything yet.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg"><Link href={`/cars/${vehicle.id}/offer/submitted?amount=${amount}`}>View Offer</Link></Button><Button asChild variant="outline" size="lg"><Link href={`/cars/${vehicle.id}`}>Back to Car</Link></Button></div></div><aside className="lg:sticky lg:top-6 lg:self-start"><OfferVehicleSummary vehicle={vehicle} /></aside></div></section></main>;
}
