import type { InspectionReport } from "./types";

const image = "/images/trusted-car-hero-placeholder.png";

export const inspectionReports: InspectionReport[] = [{
  vehicleId: "hyundai-creta-2021", vehicleName: "2021 Hyundai Creta SX", make: "Hyundai", model: "Creta", registrationNumber: "TN 01 AB 1234", inspectionDate: "Sample date", reportId: "TC-INSP-000124", overallScore: 96, condition: "Excellent condition",
  categories: [
    { id: "engine", title: "Engine & Transmission", score: 96, status: "passed", summary: "Normal operation observed in sample checks." },
    { id: "exterior", title: "Exterior & Body", score: 94, status: "attention", summary: "Minor rear bumper repair noted in sample data." },
    { id: "brakes", title: "Brakes & Tyres", score: 91, status: "attention", summary: "Brake pad wear noted for attention." },
    { id: "suspension", title: "Suspension & Steering", score: 95, status: "passed", summary: "No concerning sample observations." },
    { id: "electrical", title: "Electrical", score: 98, status: "passed", summary: "Core functions checked in sample data." },
    { id: "interior", title: "Interior & Comfort", score: 97, status: "passed", summary: "Interior condition is well maintained." },
    { id: "documents", title: "Documents", score: 100, status: "verified", summary: "Sample document checks complete." },
    { id: "road-test", title: "Road Test", score: 94, status: "checked", summary: "Sample road test observations recorded." },
  ],
  sections: [
    { id: "engine", title: "Engine & Transmission", score: 96, status: "passed", summary: "Normal operation observed in sample checks.", items: [{ label: "Engine starting", status: "passed", finding: "Engine starts normally" }, { label: "Engine noise", status: "passed", finding: "No abnormal engine noise observed" }, { label: "Oil leakage", status: "attention", finding: "Minor oil seepage — needs attention" }, { label: "Coolant leakage", status: "passed", finding: "No coolant leakage observed" }, { label: "Transmission operation", status: "passed", finding: "Transmission shifts normally" }, { label: "Clutch/gear response", status: "passed", finding: "Gear response normal during sample check" }, { label: "Engine warning lights", status: "passed", finding: "No warning lights observed" }] },
    { id: "exterior", title: "Exterior & Body", score: 94, status: "attention", summary: "Minor rear bumper repair noted in sample data.", items: [{ label: "Paint condition", status: "attention", finding: "Minor paint repair detected on rear bumper" }, { label: "Panel alignment", status: "passed", finding: "Panel alignment normal" }, { label: "Bumper condition", status: "attention", finding: "Rear bumper cosmetic repair noted" }, { label: "Windshield", status: "passed", finding: "No visible cracks observed" }, { label: "Lights", status: "passed", finding: "Headlights functioning" }, { label: "Accident indicators", status: "passed", finding: "No major accident indicators in sample inspection" }] },
    { id: "brakes", title: "Brakes & Tyres", score: 91, status: "attention", summary: "Brake pad wear noted for attention.", items: [{ label: "Front brake", status: "attention", finding: "Front brake pads approximately 40% remaining" }, { label: "Rear brake", status: "passed", finding: "Rear brake response normal" }, { label: "Brake discs", status: "passed", finding: "No abnormal visible wear noted" }, { label: "Tyre condition", status: "passed", finding: "Tyres show acceptable tread" }, { label: "Spare tyre", status: "checked", finding: "Spare tyre visually checked" }, { label: "Tyre damage", status: "passed", finding: "No visible tyre damage" }] },
    { id: "suspension", title: "Suspension & Steering", score: 95, status: "passed", summary: "No concerning sample observations.", items: [{ label: "Steering response", status: "passed", finding: "Steering response normal" }, { label: "Suspension noise", status: "passed", finding: "No abnormal noise observed" }, { label: "Shock absorbers", status: "checked", finding: "Visual sample check completed" }, { label: "Alignment", status: "passed", finding: "Vehicle tracks normally in sample road test" }] },
    { id: "electrical", title: "Electrical", score: 98, status: "passed", summary: "Core functions checked in sample data.", items: [{ label: "Battery", status: "passed", finding: "Battery response normal" }, { label: "AC", status: "passed", finding: "Air conditioning functioning" }, { label: "Infotainment", status: "passed", finding: "Infotainment powers on" }, { label: "Power windows", status: "passed", finding: "Power windows functioning" }, { label: "Central locking", status: "passed", finding: "Central locking checked" }, { label: "Warning lights", status: "passed", finding: "No active warning lights observed" }] },
    { id: "interior", title: "Interior & Comfort", score: 97, status: "passed", summary: "Interior condition is well maintained.", items: [{ label: "Seats", status: "passed", finding: "Seat condition well maintained" }, { label: "Dashboard", status: "passed", finding: "Dashboard condition normal" }, { label: "Air conditioning", status: "passed", finding: "Cooling observed during sample check" }, { label: "Interior condition", status: "passed", finding: "Interior shows normal use" }, { label: "Safety equipment", status: "not-checked", finding: "Detailed safety equipment check not included in this sample" }] },
    { id: "road-test", title: "Road Test", score: 94, status: "checked", summary: "Sample road test observations recorded.", items: [{ label: "Braking", status: "passed", finding: "Braking response normal" }, { label: "Steering", status: "passed", finding: "Steering response normal" }, { label: "Acceleration", status: "passed", finding: "Acceleration smooth" }, { label: "Gear changes", status: "passed", finding: "Gear changes normal" }, { label: "Suspension", status: "passed", finding: "No unusual behaviour observed" }, { label: "Noise", status: "checked", finding: "Normal cabin noise noted" }] },
  ],
  issues: [{ text: "Front brake pads approximately 40% remaining", status: "attention" }, { text: "Minor paint repair on rear bumper", status: "attention" }, { text: "Minor oil seepage detected", status: "attention" }],
  positives: [{ text: "No major accident indicators in sample inspection", status: "passed" }, { text: "Engine starts normally", status: "passed" }, { text: "Transmission operating normally", status: "passed" }, { text: "RC/ownership sample checks complete", status: "verified" }, { text: "Tyres in acceptable condition", status: "passed" }],
  documents: [{ name: "RC", status: "verified", note: "Sample verification recorded" }, { name: "Ownership", status: "verified", note: "Sample verification recorded" }, { name: "Insurance", status: "verified", note: "Sample verification recorded" }, { name: "Hypothecation", status: "checked", note: "Clear in sample data" }, { name: "Challans", status: "checked", note: "Checked in sample data" }],
  odometer: { value: "42,800 km", status: "checked", note: "Current odometer information is sample development data." }, inspector: { name: "Arun Kumar", id: "TC-INSP-021", date: "Sample date", status: "Sample report" },
  photos: [{ id: "exterior", category: "Exterior", src: image, alt: "Sample exterior vehicle evidence" }, { id: "engine-photo", category: "Engine", src: image, alt: "Sample engine evidence" }, { id: "interior-photo", category: "Interior", src: image, alt: "Sample interior evidence" }, { id: "tyres", category: "Tyres", src: image, alt: "Sample tyre evidence" }, { id: "documents-photo", category: "Documents", src: image, alt: "Sample document evidence" }],
}];

export function getInspectionReport(vehicleId: string) { return inspectionReports.find((report) => report.vehicleId === vehicleId); }
