import Link from "next/link";
import { ArrowLeft, Download, Share2 } from "lucide-react";
import { Button, Card, CardContent } from "@/components/ui";
import { DocumentVerificationCard } from "./components/document-verification-card";
import { InspectionCategoryCard } from "./components/inspection-category-card";
import { InspectionFinding } from "./components/inspection-finding";
import { InspectionPhotoGallery } from "./components/inspection-photo-gallery";
import { InspectionScore } from "./components/inspection-score";
import { InspectionSection } from "./components/inspection-section";
import { InspectionStatus } from "./components/inspection-status";
import { InspectorCard } from "./components/inspector-card";
import type { InspectionReport } from "./types";

function BuyerActions({ vehicleId, sticky = false }: { vehicleId: string; sticky?: boolean }) {
  return <div className={sticky ? "fixed inset-x-0 bottom-0 z-40 border-t bg-surface/95 p-3 backdrop-blur lg:hidden" : "hidden lg:block lg:sticky lg:top-6"}><Card className="shadow-raised"><CardContent className="p-6"><p className="text-xs font-black uppercase tracking-[0.16em] text-brand">Next step</p><h2 className="mt-3 text-2xl font-black">Ready to make an offer?</h2><p className="mt-3 text-sm leading-6 text-muted">Review the sample report, then continue to the future offer flow when you are ready.</p><Button asChild size="lg" className="mt-6 w-full"><Link href={`/cars/${vehicleId}/offer`}>Make an Offer</Link></Button><Button asChild variant="outline" size="lg" className="mt-3 w-full"><Link href={`/cars/${vehicleId}`}>Back to Car</Link></Button></CardContent></Card></div>;
}

export function InspectionReportPage({ report }: { report: InspectionReport }) {
  return <main className="bg-ivory pb-24 lg:pb-0">
    <div className="border-b bg-surface px-4 py-4 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl items-center gap-2 text-sm text-muted"><Link href="/browse-cars" className="inline-flex items-center gap-1 font-bold hover:text-brand"><ArrowLeft aria-hidden="true" size={16} />Browse Cars</Link><span>/</span><Link href={`/cars/${report.vehicleId}`} className="hover:text-brand">{report.vehicleName}</Link><span>/</span><span className="text-ink">Inspection Report</span></div></div>
    <section className="border-b bg-charcoal px-4 py-10 text-ivory sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="inline-flex rounded-full bg-brand/25 px-3 py-1.5 text-xs font-black uppercase tracking-[0.12em] text-ivory">Sample Development Report</p><h1 className="mt-6 font-display text-4xl font-black uppercase leading-[0.94] tracking-[-0.05em] sm:text-6xl">Vehicle Inspection Report</h1><p className="mt-5 text-xl font-black">{report.vehicleName}</p><div className="mt-5 flex flex-wrap gap-x-7 gap-y-2 text-sm text-ivory/70"><span>{report.registrationNumber}</span><span>Inspection date: {report.inspectionDate}</span><span>Report ID: {report.reportId}</span></div></div></section>

    <section className="px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[minmax(0,1fr)_340px]"><div className="space-y-10"><InspectionScore score={report.overallScore} condition={report.condition} /><section><h2 className="text-xl font-black">Inspection status legend</h2><div className="mt-4 flex flex-wrap gap-2"><InspectionStatus status="verified" /><InspectionStatus status="passed" /><InspectionStatus status="attention" /><InspectionStatus status="checked" /><InspectionStatus status="not-checked" /></div></section><section><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-brand">Sample inspection summary</p><h2 className="mt-2 font-display text-4xl font-black uppercase tracking-[-0.05em]">What was checked</h2></div><p className="text-sm text-muted">Scores and statuses are sample development data.</p></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{report.categories.map((category) => <InspectionCategoryCard key={category.id} category={category} />)}</div></section><section><p className="text-xs font-black uppercase tracking-[0.16em] text-brand">Detailed sample report</p><h2 className="mt-2 font-display text-4xl font-black uppercase tracking-[-0.05em]">Inspection details</h2><div className="mt-7 space-y-4">{report.sections.map((section) => <InspectionSection key={section.id} section={section} />)}</div></section></div><BuyerActions vehicleId={report.vehicleId} /></div></section>

    <section className="bg-surface px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-6 lg:grid-cols-2"><Card className="border-brand/30 bg-brand/5"><CardContent className="p-7"><p className="text-xs font-black uppercase tracking-[0.16em] text-brand">Sample findings</p><h2 className="mt-3 text-3xl font-black">Needs Attention</h2><p className="mt-2 text-sm text-muted">These sample observations are shown prominently for transparency.</p><ul className="mt-6 space-y-4">{report.issues.map((finding) => <InspectionFinding key={finding.text} finding={finding} />)}</ul></CardContent></Card><Card><CardContent className="p-7"><p className="text-xs font-black uppercase tracking-[0.16em] text-success">Sample findings</p><h2 className="mt-3 text-3xl font-black">What looks good</h2><p className="mt-2 text-sm text-muted">Positive observations from the sample report.</p><ul className="mt-6 space-y-4">{report.positives.map((finding) => <InspectionFinding key={finding.text} finding={finding} />)}</ul></CardContent></Card></div></div></section>

    <section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1.1fr_0.9fr]"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-brand">Sample document checks</p><h2 className="mt-2 font-display text-4xl font-black uppercase tracking-[-0.05em]">Documents &amp; ownership</h2><div className="mt-7 grid gap-4 sm:grid-cols-2">{report.documents.map((document) => <DocumentVerificationCard key={document.name} document={document} />)}</div><Card className="mt-4"><CardContent className="flex flex-col gap-4 p-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-brand">Odometer</p><p className="mt-2 text-3xl font-black">{report.odometer.value}</p><p className="mt-2 text-sm text-muted">{report.odometer.note}</p></div><InspectionStatus status={report.odometer.status} /></CardContent></Card></div><InspectorCard inspector={report.inspector} /></div></section>

    <section className="bg-surface px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-brand">Sample inspection evidence</p><h2 className="mt-2 font-display text-4xl font-black uppercase tracking-[-0.05em]">Photos from the report</h2></div><div className="flex gap-2"><Button variant="outline" size="sm"><Share2 aria-hidden="true" size={16} />Share Report</Button><Button variant="outline" size="sm"><Download aria-hidden="true" size={16} />Download Report</Button></div></div><p className="mt-3 text-sm text-muted">Sharing and download are UI actions only in this development build.</p><div className="mt-7"><InspectionPhotoGallery photos={report.photos} /></div></div></section>

    <footer className="bg-ink px-4 py-9 text-ivory/70 sm:px-6 lg:px-8"><p className="mx-auto max-w-7xl text-sm leading-6">Inspection reports are based on the checks performed during the inspection. Buyers should review the complete report and may request an additional inspection before completing a transaction.</p></footer>
    <BuyerActions vehicleId={report.vehicleId} sticky />
  </main>;
}
