import Link from "next/link";
import { AlertCircle, ArrowLeft, CheckCircle2, ClipboardCheck, FileCheck2, Gauge, Share2, ShieldCheck, type LucideIcon } from "lucide-react";
import { Badge, Button, Card, CardContent, CardHeader, Status } from "@/components/ui";
import { vehicles } from "@/features/browse-cars/data";
import { VehicleCard } from "@/features/browse-cars/vehicle-card";
import { InspectionScore } from "./inspection-score";
import { TransactionTimeline } from "./transaction-timeline";
import type { VehicleDetails } from "./types";
import { VehicleGallery } from "./vehicle-gallery";

const lakhFormatter = new Intl.NumberFormat("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const kilometreFormatter = new Intl.NumberFormat("en-IN");
const price = (value: number) => `₹${lakhFormatter.format(value / 100000)} Lakh`;
const trustItems: { icon: LucideIcon; label: string }[] = [
  { icon: ClipboardCheck, label: "250+ point inspection" }, { icon: FileCheck2, label: "Document verification" }, { icon: ShieldCheck, label: "Ownership verification" },
  { icon: Gauge, label: "Loan & challan check" }, { icon: ShieldCheck, label: "Secure transaction support" }, { icon: FileCheck2, label: "RC transfer assistance" },
];

export function CarDetailsPage({ vehicle }: { vehicle: VehicleDetails }) {
  const relatedVehicles = vehicles.filter((item) => item.id !== vehicle.id).slice(0, 3);
  const specs: [string, string | number][] = [["Registration year", vehicle.year], ["Manufacturing year", vehicle.manufacturingYear], ["Kilometres", `${kilometreFormatter.format(vehicle.kilometres)} km`], ["Fuel", vehicle.fuel], ["Transmission", vehicle.transmission], ["Ownership", vehicle.ownership], ["Engine", vehicle.engine], ["Color", vehicle.color], ["Registration city", vehicle.city]];
  return <main className="bg-ivory pb-24 lg:pb-0">
    <div className="border-b bg-surface px-4 py-4 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl items-center gap-2 text-sm text-muted"><Link href="/browse-cars" className="inline-flex items-center gap-1 font-bold hover:text-brand"><ArrowLeft aria-hidden="true" size={16} />Browse Cars</Link><span>/</span><span>{vehicle.make}</span><span>/</span><span className="text-ink">{vehicle.model}</span></div></div>
    <div className="border-b bg-brand/10 px-4 py-2.5 text-center text-xs font-bold text-brand"><span className="inline-flex items-center gap-1.5"><AlertCircle aria-hidden="true" size={15} />All vehicle, inspection and verification details on this page are sample development data.</span></div>

    <section className="px-4 py-7 sm:px-6 lg:px-8 lg:py-10"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[minmax(0,1.6fr)_minmax(320px,0.8fr)]"><VehicleGallery images={vehicle.gallery} name={vehicle.name} /><aside className="lg:sticky lg:top-6 lg:self-start"><Badge variant="verified">Verified Car · sample data</Badge><h1 className="mt-4 font-display text-4xl font-black uppercase leading-[0.94] tracking-[-0.05em] sm:text-5xl">{vehicle.name}</h1><p className="mt-4 text-3xl font-black text-brand">{price(vehicle.price)}</p><p className="mt-4 text-base font-medium text-muted">{kilometreFormatter.format(vehicle.kilometres)} km <span aria-hidden="true">·</span> {vehicle.fuel} <span aria-hidden="true">·</span> {vehicle.transmission} <span aria-hidden="true">·</span> {vehicle.city}</p><div className="mt-6 grid grid-cols-2 gap-3"><Card><CardContent className="p-4"><p className="text-xs font-bold text-muted">Inspection score</p><p className="mt-1 text-2xl font-black text-success">{vehicle.inspectionScore}/100</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs font-bold text-muted">Ownership</p><p className="mt-1 text-sm font-black">{vehicle.ownership}</p></CardContent></Card></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-1"><Button size="lg">Make an Offer</Button><Button variant="outline" size="lg"><Share2 aria-hidden="true" size={18} />Share Car</Button></div><p className="mt-4 text-xs leading-5 text-muted">Offers are not active in this development build.</p></aside></div></section>

    <section className="bg-surface px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[0.16em] text-brand">Trusted Car process</p><h2 className="mt-3 font-display text-4xl font-black uppercase tracking-[-0.05em]">Verified before you buy</h2><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{trustItems.map(({ icon: Icon, label }) => <Card key={label}><CardContent className="flex items-center gap-4 p-5"><Icon aria-hidden="true" className="text-brand" size={24} /><span className="font-black">{label}</span></CardContent></Card>)}</div></div></section>

    <section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1.1fr_0.9fr]"><div><div className="mb-5"><p className="text-xs font-black uppercase tracking-[0.16em] text-brand">Sample inspection report</p><h2 className="mt-3 font-display text-4xl font-black uppercase tracking-[-0.05em]">Condition, clearly explained.</h2></div><InspectionScore score={vehicle.inspectionScore} condition={vehicle.inspectionCondition} categories={vehicle.inspectionCategories} /></div><Card className="self-end"><CardHeader><h2 className="text-xl font-black">Inspection highlights</h2><p className="mt-1 text-sm text-muted">Sample development data only</p></CardHeader><CardContent className="space-y-4 p-6">{vehicle.inspectionFindings.map((finding) => <div key={finding.text} className="flex gap-3 text-sm"><CheckCircle2 aria-hidden="true" size={19} className={finding.state === "positive" ? "shrink-0 text-success" : "shrink-0 text-brand"} /><span>{finding.text}</span></div>)}</CardContent></Card></div></section>

    <section className="bg-surface px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2"><Card><CardHeader><h2 className="text-xl font-black">Vehicle specifications</h2><p className="mt-1 text-sm text-muted">Sample development data only</p></CardHeader><CardContent className="grid grid-cols-2 gap-x-6 gap-y-5 p-6 sm:grid-cols-3">{specs.map(([label, value]) => <div key={label}><p className="text-xs font-bold text-muted">{label}</p><p className="mt-1 text-sm font-black">{value}</p></div>)}</CardContent></Card><Card><CardHeader><h2 className="text-xl font-black">Documents &amp; verification</h2><p className="mt-1 text-sm text-muted">Sample development data only</p></CardHeader><CardContent className="space-y-3 p-6">{vehicle.documents.map((document) => <div key={document.label} className="flex items-center justify-between border-b pb-3 last:border-0 last:pb-0"><span className="text-sm font-bold">{document.label}</span><Status status="verified" label={document.status} /></div>)}</CardContent></Card></div></section>

    <section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-3"><Card className="lg:col-span-2"><CardContent className="p-7 sm:p-9"><p className="text-xs font-black uppercase tracking-[0.16em] text-brand">Sample offer guidance</p><h2 className="mt-3 font-display text-4xl font-black uppercase tracking-[-0.05em]">Ready to make an offer?</h2><div className="mt-7 grid gap-5 sm:grid-cols-2"><div><p className="text-sm font-bold text-muted">Seller asking price</p><p className="mt-1 text-2xl font-black">{price(vehicle.price)}</p></div><div><p className="text-sm font-bold text-muted">Recommended offer range</p><p className="mt-1 text-2xl font-black">{price(vehicle.recommendedOffer.low)} – {price(vehicle.recommendedOffer.high)}</p></div></div><Button size="lg" className="mt-8">Make an Offer</Button></CardContent></Card><Card className="bg-charcoal text-ivory"><CardContent className="p-7"><p className="text-xs font-black uppercase tracking-[0.16em] text-success">Finance teaser</p><h2 className="mt-4 text-3xl font-black">Need finance?</h2><p className="mt-3 leading-7 text-ivory/70">Check financing options from our lending partners.</p><Button variant="outline" className="mt-8 border-ivory text-ivory hover:bg-ivory hover:text-ink">Explore Finance</Button></CardContent></Card></div></section>

    <section className="bg-surface px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-[1.2fr_0.8fr]"><Card><CardContent className="p-7"><p className="text-xs font-black uppercase tracking-[0.16em] text-brand">Transaction process</p><h2 className="mt-3 text-2xl font-black">One protected transaction</h2><div className="mt-8"><TransactionTimeline /></div></CardContent></Card><Card><CardContent className="p-7"><Badge variant="verified">Verified seller · sample data</Badge><h2 className="mt-5 text-2xl font-black">Seller information</h2><p className="mt-5 text-sm"><span className="font-bold text-muted">Seller since </span>{vehicle.seller.since}</p><p className="mt-3 text-sm"><span className="font-bold text-muted">Response </span>{vehicle.seller.response}</p></CardContent></Card></div></section>

    <section className="bg-ink px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl rounded-xl border border-white/15 bg-charcoal p-7 text-ivory sm:p-10"><ShieldCheck aria-hidden="true" className="text-success" size={30} /><h2 className="mt-5 font-display text-4xl font-black uppercase tracking-[-0.05em]">Your transaction is protected</h2><p className="mt-4 max-w-2xl leading-7 text-ivory/70">Payment and transfer support are coordinated through the Trusted Car transaction process, from accepted offer through vehicle handover and RC transfer assistance.</p></div></section>

    <section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[0.16em] text-brand">More to consider</p><h2 className="mt-3 font-display text-4xl font-black uppercase tracking-[-0.05em]">Related verified cars</h2><div className="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{relatedVehicles.map((item) => <VehicleCard key={item.id} vehicle={item} />)}</div></div></section>
    <div className="fixed inset-x-0 bottom-0 z-40 border-t bg-surface/95 p-3 backdrop-blur lg:hidden"><Button size="lg" className="w-full">Make an Offer</Button></div>
  </main>;
}
